### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [tinaylee/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tinaylee** [comment]
Hi Ken, I think I've figured it out the mobile meta tag, looks ok when I view on mobile now, let me know if you're still seeing the problem.

**Comment by kenmazaika** [comment]
Thumbs up!  I see the tag in your `application.html.erb` and it looks perfect.
